name: data-curation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pinocchio
  - numpy
  - pandas
  - pyarrow
  - matplotlib
  - scipy
  - pyyaml
  - pip
  - pip:
    - huggingface_hub
